version: "3"

networks:
    mdm-network:
        driver: bridge
        external: true

services:
    etcd:
        build: ./etcd
        networks:  
            mdm-network:
                ipv4_address: 172.19.0.4
        container_name: mdm-etcd
        hostname: etcd
        command: etcd
        environment:
            ETCD_NAME: etcd0
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.19.0.4:2380
            ETCD_INITIAL_CLUSTER: etcd0=http://172.19.0.4:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-01
            ETCD_LISTEN_PEER_URLS: http://172.19.0.4:2380
            ETCD_LISTEN_CLIENT_URLS: http://172.19.0.4:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://172.19.0.4:2379
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == floitet]
    haproxy:
        build: ./haproxy
        networks:  
            mdm-network:
                ipv4_address: 172.19.0.5
        container_name: mdm-haproxy
        ports:
            - 5000:5000
            - 7000:7000
        hostname: haproxy
        deploy:
            mode: replicated
            replicas: 1
            placement: 
                constraints: [node.hostname == floitet]