version: "3"
networks:
    mdm-network: 
        external: true

services:
    patroni1:
        build: ./patroni
        networks:  
            mdm-network:
                ipv4_address: 172.19.0.2
        ports:
            - 5441:5432
            - 8091:8091
        hostname: patroni1
        volumes:
          - /patroni1:/data/patroni
        environment:
            PATRONI_API_CONNECT_PORT: 8091
            REPLICATION_NAME: replicator 
            REPLICATION_PASS: replicate
            SU_NAME: postgres
            SU_PASS: postgres
            POSTGRES_APP_ROLE_PASS: admin
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == floitet]
    patroni2:
        build: ./patroni
        networks:  
            mdm-network:
                ipv4_address: 172.19.0.3
        ports:
            - 5442:5432
            - 8092:8091
        hostname: patroni2
        volumes:
          - /patroni2:/data/patroni
        environment:
            PATRONI_API_CONNECT_PORT: 8091
            REPLICATION_NAME: replicator 
            REPLICATION_PASS: replicate
            SU_NAME: postgres
            SU_PASS: postgres
            POSTGRES_APP_ROLE_PASS: admin
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == floitet]